version: "3.8"

services:
  prisma-console-app-dev:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prisma-console-app-dev
